# Custom Language File for Launcher Customizer

[ejs.app]
title = "GuildCraft Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/GuildCraft/GCLauncher"
mediaTwitterURL = ""
mediaInstagramURL = ""
mediaYouTubeURL = "https://www.youtube.com/@guildcraftnetwork1"
mediaDiscordURL = "https://discord.gg/guildcraft"

[ejs.settings]
sourceGithubLink = "https://github.com/GuildCraft/GCLauncher"
supportLink = "https://github.com/GuildCraft/GCLauncher/issues"
selectLanguage = "Select a Language"
changeLanguageTitle = "Change the launcher language"
changeLanguageDesc = "You can change the language in the list below. This text will not change if you change the language so you can find your wayback here to change it back"

[ejs.welcome]
welcomeHeader = "WELCOME TO GUILDCRAFT"
welcomeDescription = "<Insert guildcraft text here>" 
welcomeDescCTA = "Your adventure awaits you today."

[ejs.overlay]
changedLanguageHeader = "You changed the previous language"